version: '3.7'
services:
        mysql:
                image: postgres:11.4-alpine 
                env_file:
                        - .env
                ports:
                        - ${DB_HOST}:${DB_PORT}:5432
                volumes:
                        - ./tmp/postgres:/var/lib/postgresql/data
                environment:
                        - POSTGRES_USER=${DB_USER}
                        - POSTGRES_PASSWORD=${DB_PASS}
                        - POSTGRES_DB=${DB_NAME}
